In [1]:
pip install pyspark

SyntaxError: invalid syntax (<ipython-input-1-1b249d5f4e3b>, line 1)

In [2]:
import pyspark

In [1]:
name = input("Type in your name : ")

Type in your name : jeong ii tae


In [2]:
print("My name is " , name)

My name is  jeong ii tae


In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [6]:
pip install numpy

  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
    100% |████████████████████████████████| 20.2MB 80kB/s  eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [2]:
aArray = np.array(blist)

NameError: name 'blist' is not defined

In [3]:
bList = (1 ,3 , 5, 7, 9)

In [4]:
aArray = np.array([2, 4, 6 ,8])

In [5]:
print(aArray)

[2 4 6 8]


In [7]:
bArray = aArray * 3

In [8]:
print(bArray)

[ 6 12 18 24]


In [9]:
za = np.zeros(5)

In [10]:
print(za)

[0. 0. 0. 0. 0.]


In [13]:
za_1 = np.zeros([5,2])

In [14]:
za_1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
oa = np.ones(5)

In [16]:
oa

array([1., 1., 1., 1., 1.])

In [18]:
oa_1 = np.ones([5,2])

In [19]:
oa_1

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
python --version

NameError: name 'python' is not defined

In [24]:
myArray = np.arange(0, 40)

In [25]:
myArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [26]:
myArray.reshape(5,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [27]:
myArray.reshape(5,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [28]:
mat2 = myArray.reshape(5,8)

In [53]:
mat3 = np.arange(0, 54)

In [54]:
mat3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [51]:
mat3 = np.reshape()

In [47]:
print(mat3)

[2]


In [55]:
myMatrix = np.array(range(0,24))

In [56]:
myMatrix

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
myMatrix = myMatrix.reshape([3,8])

In [58]:
myMatrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [60]:
myMatrix[2,-1]

23

In [61]:
myMatrix[2]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [62]:
myMatrix[2,]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [63]:
myMatrix[2, :]

array([16, 17, 18, 19, 20, 21, 22, 23])

In [64]:
myMatrix[1,:]

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
myMatrix.dtype

dtype('int64')

In [66]:
myMatrix.mean

<function ndarray.mean>

In [69]:
myMatrix.mean()

11.5

In [70]:
np.apply_along_axis(np.mean, axis=0 , arr=myMatrix)

array([ 8.,  9., 10., 11., 12., 13., 14., 15.])

In [71]:
myMatrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [73]:
np.apply_along_axis(np.mean, axis=1 , arr=myMatrix)

array([ 3.5, 11.5, 19.5])